version: "3.5"
   
services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=conasis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: ash -c "python3 manage.py migrate && python3 manage.py createsuperuser && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - conasis_vol:/home/proyecto/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_vol:
  conasis_vol:

    
