# Generated by Django 3.2.4 on 2021-06-15 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuarios_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='tipo',
        ),
    ]
