# Generated by Django 3.2.4 on 2021-06-15 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuarios_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.tiposusuarios', verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
