# Generated by Django 3.2.4 on 2021-06-28 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuarios_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.tiposusuarios', verbose_name='Tipo'),
        ),
    ]
